
package com.bio4j.model.enums;

/**
 *
 * @author Pablo Pareja Tobes <ppareja@era7.com>
 */
public enum UniprotDBXref {
        
    ALLERGOME("protein_allergome_references","Allergome"),
    ARACHNO_SERVER("protein_arachnoserver_references","ArachnoServer"),
    ARRAY_EXPRESS("protein_array_express_references","ArrayExpress"), 
    BGEE("protein_bgee_references","Bgee"),
    BINDING_DB("protein_binding_db_references","BindingDB"),
    BIOCYC("protein_biocyc_references","BioCyc"),
    BRENDA("protein_brenda_references","BRENDA"), 
    CAZY("protein_cazy_references","CAZy"),
    CGD("protein_cgd_references", "CGD"),
    CHEMBL("protein_chembl_references", "ChEMBL"),
    CHITARS("protein_chitars_references","ChiTaRS"),
    CLEANEX("protein_cleanex_references","CleanEx"),
    COMPLUYEAST_2D_PAGE("protein_compluyeast_2dpage_references","COMPLUYEAST-2DPAGE"), 
    CONO_SERVER("protein_conoserver_references","ConoServer"),
    CTD("protein_ctd_references", "CTD"),
    CYGD("protein_cygd_references","CYGD"),
    DBSNP("protein_dbsnp_references","dbSNP"), 
    DDBJ("protein_ddbj_references","DDBJ"), 
    DICTY_BASE("protein_dicty_base_references","dictyBase"),
    DIP("protein_dip_references","DIP"), 
    DISPROT("protein_dip_references","DisProt"), 
    DMDM("protein_dmdm_references","DMDM"), 
    DNASU("protein_dnasu_references","DNASU"), 
    DOSAC_COBS_2D_PAGE("protein_dosac_cobs_2dpage_references","DOSAC-COBS-2DPAGE"),
    DRUG_BANK("protein_drugbank_references","DrugBank"),
    ECHO_BASE("protein_echobase_references","EchoBASE"), 
    ECO_GENE("protein_ecogene_references","EcoGene"), 
    EGGNOG("protein_eggnog_references","eggNOG"),      
    EMBL("protein_embl_references","EMBL"), 
    ENSEMBL("protein_ensembl_references", "Ensembl"),
    ENSEMBL_BACTERIA("protein_ensembl_bacteria_references","EnsemblBacteria"), 
    ENSEMBL_FUNGI("protein_ensembl_fungi_references","EnsemblFungi"), 
    ENSEMBL_METAZOA("protein_ensembl_metazoa_references","EnsemblMetazoa"), 
    ENSEMBL_PLANTS("protein_ensembl_plants_references", "EnsemblPlants"), 
    ENSEMBL_PROTISTS("protein_ensembl_protists_references","EnsemblProtists"),
    EUHCV_DB("protein_euhcvdb_references","euHCVdb"),
    EUPATH_DB("protein_eupathdb_references","EuPathDB"), 
    EVOLUTIONARY_TRACE("protein_evolutionary_trace_references","EvolutionaryTrace"), 
    FLYBASE("protein_flybase_references","FlyBase"), 
    GENATLAS("protein_genatlas_references","GenAtlas"), 
    GENBANK("protein_genbank_references","GenBank"), 
    GENE3D("protein_gene3d_references","Gene3D"), 
    GENECARDS("protein_genecards_references","GeneCards"), 
    GENEFARM("protein_genefarm_references","GeneFarm"), 
    GENEID("protein_geneid_references","GeneID"), 
    GENETREE("protein_genetree_references","GeneTree"), 
    GENEVESTIGATOR("protein_genevestigator_references","Genevestigator"),
    GENOLIST("protein_genolist_references","GenoList"), 
    GENOME_REVIEWS("protein_genome_reviews_references","GenomeReviews"),
    GENOME_RNAI("protein_genome_rnai_references","GenomeRNAi"),
    GERMONLINE("protein_germonline_references","GermOnline"), 
    GLYCO_SUITE_DB("protein_glycosuitedb_references","GlycoSuiteDB"), 
    GPCR_DB("protein_gpcrdb_references","GPCRDB"), 
    GRAMENE("protein_gramene_references","Gramene"), 
    HINV_DB("protein_hinvdb_references","H-InvDB"), 
    HAMAP("protein_hamap_references","HAMAP"),
    HGNC("protein_hgnc_references","HGNC"), 
    HOGENOM("protein_hogenom_references","HOGENOM"), 
    HOVERGEN("protein_hovergen_references","HOVERGEN"),
    HPA("protein_hpa_references","HPA"),
    HSSP("protein_hssp_references","HSSP"), 
    HUGE("protein_huge_references","HUGE"),
    IMGT("protein_imgt_references","IMGT"),
    INPARANOID("protein_inparanoid_references","InParanoid"),
    INTACT("protein_intact_references","IntAct"), 
    IPI("protein_ipi_references","IPI"), 
    KEGG("protein_kegg_references","KEGG"),    
    KO("protein_ko_references","KO"), 
    LEGIOLIST("protein_legio_list_references","LegioList"), 
    LEPROMA("protein_leproma_references","Leproma"),
    MAIZEGD_DB("protein_maize_gdb_references","MaizeGDB"),
    MEROPS("protein_merops_references","MEROPS"), 
    MGI("protein_mgi_references","MGI"), 
    MICADO("protein_micado_references","Micado"), 
    MIM("protein_mim_references","MIM"), 
    MINT("protein_mint_references","MINT"), 
    MODBASE("protein_modbase_references","ModBase"), 
    MYCOCLAP("protein_mycoclap_references","mycoCLAP"), 
    NEXTBIO("protein_nextbio_references","NextBio"), 
    NEXTPROT("protein_nextprot_references","neXtProt"), 
    OGP("protein_ogp_references","OGP"), 
    OMA("protein_oma_references","OMA"), 
    ORPHANET("protein_orphanet_references","Orphanet"), 
    ORTHO_DB("protein_orthodb_references","OrthoDB"), 
    PANTHER("protein_panther_references","PANTHER"), 
    PATHWAY_INTERACTION_DB("protein_pathway_interaction_db_references","Pathway_Interaction_DB"),
    PATRIC("protein_patric_references","PATRIC"), 
    PAXDB("protein_paxdb_references","PaxDb"), 
    PDB("protein_pdb_references","PDB"), 
    PDBJ("protein_pdbj_references","PDBj"), 
    PDBSUM("protein_pdbsum_references","PDBsum"), 
    PEPTIDE_ATLAS("protein_peptide_atlas_references","PeptideAtlas"), 
    PEROXIBASE("protein_peroxibase_references","PeroxiBase"), 
    PHARM_GKB("protein_pharmgkb_references","PharmGKB"), 
    PHOSPHOSITE("protein_phosphosite_references","PhosphoSite"), 
    PHOS_SITE("protein_phos_site_references","PhosSite"), 
    PHYLOME_DB("protein_phylome_db_references","PhylomeDB"), 
    PIR("protein_pir_references","PIR"), 
    PIRSF("protein_pirsf_references","PIRSF"), 
    PMAP_CUT_DB("protein_pmap_cutdb_references","PMAP-CutDB"), 
    POMBASE("protein_pombase_references","PomBase"),
    PPTASE_DB("protein_pptasedb_references","PptaseDB"),
    PRIDE("protein_pride_references","PRIDE"), 
    PRINTS("protein_prints_references","PRINTS"), 
    PRODOM("protein_prodom_references","ProDom"), 
    PROMEX("protein_promex_references","ProMEX"), 
    PROSITE("protein_prosite_references","PROSITE"), 
    PROT_CLUST_DB("protein_prot_clust_db_references","ProtClustDB"), 
    PROTEIN_MODEL_PORTAL("protein_model_portal_references","ProteinModelPortal"), 
    PROTONET("protein_protonet_references","ProtoNet"), 
    PSEUDOCAP("protein_pseudo_cap_references","PseudoCAP"), 
    RCSBPDB("protein_rcsb_pdb_references","RCSB PDB"), 
    REBASE("protein_rebase_references","REBASE"),
    REFSEQ("protein_refseq_references","RefSeq"), 
    REPRODUCTION_2D_PAGE("protein_reproduction_2dpage_references","REPRODUCTION-2DPAGE"),
    RGD("protein_rgd_references","RGD"), 
    ROUGE("protein_rouge_references","Rouge"),
    SABIO_RK("protein_sabio_rk_references","SABIO-RK"), 
    SBKB("protein_sbkb_references","SBKB"), 
    SGD("protein_sgd_references","SGD"), 
    SMART("protein_smart_references","SMART"), 
    SMR("protein_smr_references","SMR"), 
    SOURCE("protein_source_references","SOURCE"),
    STRING("protein_string_references","STRING"), 
    SUPFAM("protein_supfam_references","SUPFAM"), 
    SWISS_2D_PAGE("protein_swiss_2dpage_references","SWISS-2DPAGE"), 
    TAIR("protein_tair_references","TAIR"), 
    TCDB("protein_tcb_references","TCDB"), 
    TIGRFAMS("protein_tigrfams_references","TIGRFAMs"), 
    TUBERCULIST("protein_tuberculist_references","TubercuList"), 
    UCD_2D_PAGE("protein_ucd_2dpage_references","UCD-2DPAGE"), 
    UCSC("protein_ucsc_references","UCSC"),
    UNIGENE("protein_unigene_references","UniGene"),
    UNIPATHWAY("protein_unipathway_references","UniPathway"), 
    VECTORBASE("protein_vector_base_references","VectorBase"), 
    WORLD_2D_PAGE("protein_world_2dpage_references","World-2DPAGE"), 
    WORMBASE("protein_worm_base_references","WormBase"), 
    XENBASE("protein_xen_base_references","Xenbase"), 
    ZFIN("protein_zfin_references","ZFIN");
    
    private final String uniprotAtributeValue;
    private final String proteinReferencePropertyName;
    
    private UniprotDBXref(String uniprotAttValue, String propertyName) {
        this.uniprotAtributeValue = uniprotAttValue;
        this.proteinReferencePropertyName = propertyName;
    }
    
    public String getProteinReferencePropertyName(){
        return proteinReferencePropertyName;
    }
    
    public String getUniprotAttributeValue(){
        return uniprotAtributeValue;
    }
}
