/*
 * Copyright (C) 2010-2013  "Bio4j"
 *
 * This file is part of Bio4j
 *
 * Bio4j is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 */
package com.era7.bioinfo.bio4j.model.nodes;

import com.era7.bioinfo.bio4j.model.nodes.citation.Article;
import com.era7.bioinfo.bio4j.model.nodes.citation.Book;
import com.era7.bioinfo.bio4j.model.nodes.citation.OnlineArticle;
import com.era7.bioinfo.bio4j.model.nodes.citation.Patent;
import com.era7.bioinfo.bio4j.model.nodes.citation.Submission;
import com.era7.bioinfo.bio4j.model.nodes.citation.Thesis;
import com.era7.bioinfo.bio4j.model.nodes.citation.UnpublishedObservation;
import com.era7.bioinfo.bio4j.model.nodes.reactome.ReactomeTerm;
import com.era7.bioinfo.bio4j.model.nodes.refseq.GenomeElement;
import com.era7.bioinfo.bio4j.model.relationships.comment.DomainComment;
import com.era7.bioinfo.bio4j.model.relationships.comment.FunctionComment;
import com.era7.bioinfo.bio4j.model.relationships.comment.PathwayComment;
import com.era7.bioinfo.bio4j.model.relationships.comment.SimilarityComment;
import com.era7.bioinfo.bio4j.model.relationships.features.ActiveSiteFeature;
import com.era7.bioinfo.bio4j.model.relationships.features.SignalPeptideFeature;
import com.era7.bioinfo.bio4j.model.relationships.features.SpliceVariantFeature;
import com.era7.bioinfo.bio4j.model.relationships.features.TransmembraneRegionFeature;
import com.era7.bioinfo.bio4j.model.relationships.protein.ProteinIsoformInteraction;
import com.era7.bioinfo.bio4j.model.relationships.protein.ProteinProteinInteraction;
import java.util.List;

/**
 *
 * @author Pablo Pareja Tobes <ppareja@era7.com>
 */
public interface Protein extends BasicNode{
 
    //---------------------------------------------------------------------------------------------
    //-------------------------------------GETTERS-------------------------------------------------
    //---------------------------------------------------------------------------------------------
    public String getName();
    public String getFullName();
    public String getShortName();
    public String getAccession();
    public String getSequence();
    public String getModifiedDate();
    public float getMass();
    public int getLength();
    public String[] getGeneNames();    
    public String[] getEnsemblReferences();
    public String[] getEMBLReferences();
    public String[] getEnsemblPlantsReferences();
    public String[] getRefseqReferences();
    public String[] getAlternativeAcessions();
    public String[] getPIRReferences();
    public String[] getKeggReferences();
    public String[] getArrayExpressReferences();
    public String[] getUniGeneReferences();    
    public String[] getDBaseEColiReferences();    
    public String[] getAarhusGhent2DPageReferences();    
    public String[] getAGDReferences();    
    public String[] getAllergomeReferences();    
    public String[] getANU2DPageReferences();    
    public String[] getArachnoServerReferences();    
    public String[] getBGeeReferences();    
    public String[] getBindingDBReferences();    
    public String[] getBioCycReferences();    
    public String[] getBrendaReferences();    
    public String[] getCazyReferences();    
    public String[] getCGDReferences();    
    public String[] getCHEMBLReferences();
    public String[] getCleanexReferences();
    public String[] getCompluyeast2DPageReferences();    
    public String[] getConoServerReferences();    
    public String[] getCornea2DPageReferences();    
    public String[] getCTDReferences();    
    public String[] getCYGDReferences();    
    public String[] getDBSNPReferences();    
    public String[] getDDBJReferences();    
    public String[] getDictyBaseReferences();    
    public String[] getDIPReferences();    
    public String[] getDisprotReferences();    
    public String[] getDMDMReferences();    
    public String[] getDnasuReferences();    
    public String[] getDosacCobs2DPageReferences();    
    public String[] getDrugBankReferences();    
    public String[] getEchoBaseReferences();    
    public String[] getEcoGeneReferences();    
    public String[] getEggnogReferences();    
    public String[] getEnsemblBacteriaReferences();    
    public String[] getEnsemblFungiReferences();    
    public String[] getEnsemblMetazoaReferences();    
    public String[] getEnsemblProtistsReferences();    
    public String[] getEUHCVDBReferences();    
    public String[] getEUPathDBReferences();    
    public String[] getEvolutionaryTraceReferences();    
    public String[] getFlybaseReferences();    
    public String[] getGenAtlasReferences();    
    public String[] getGenbankReferences();    
    public String[] getGene3DReferences();    
    public String[] getGenecardsReferences();    
    public String[] getGenefarmReferences();    
    public String[] getGeneIDReferences();    
    public String[] getGeneTreeReferences();    
    public String[] getGenevestigatorReferences();    
    public String[] getGenolistReferences();    
    public String[] getGenomeReviewsReferences();    
    public String[] getGenomeRNAIReferences();    
    public String[] getGermOnlineReferences();    
    public String[] getGlycoSuiteDBReferences();    
    public String[] getGPCRDBReferences();    
    public String[] getGrameneReferences();    
    public String[] getHINVDBReferences();   
    public String[] getHamapReferences();    
    public String[] getHGNCReferences();    
    public String[] getHogenomReferences();    
    public String[] getHovergenReferences();    
    public String[] getHPAReferences();
    public String[] getHSSPReferences();
    public String[] getHugeReferences();
    public String[] getIMGTReferences();
    public String[] getInparanoidReferences();
    public String[] getIntactReferences();
    public String[] getIPIReferences();
    public String[] getKOReferences();
    public String[] getLegioListReferences();
    public String[] getLepromaReferences();
    public String[] getMaizeGDBReferences();
    public String[] getMeropsReferences();
    public String[] getMGIReferences();
    public String[] getMicadoReferences();
    public String[] getMIMReferences();
    public String[] getMintReferences();
    public String[] getModbaseReferences();
    public String[] getMycoClapReferences();
    public String[] getNextBioReferences();
    public String[] getNextProtReferences();
    public String[] getOGPReferences();
    public String[] getOMAReferences();
    public String[] getOrphanetReferences();
    public String[] getOrthoDBReferences();
    public String[] getPantherReferences();
    public String[] getPathwayInteractionDBReferences();
    public String[] getPatricReferences();
    public String[] getPaxDBReferences();
    public String[] getPDBReferences();
    public String[] getPDBJReferences();
    public String[] getPDBSumReferences();
    public String[] getPeptideAtlasReferences();
    public String[] getPeroxibaseReferences();
    public String[] getPharmGKBReferences();
    public String[] getPhci2DPageReferences();
    public String[] getPhosphositeReferences();
    public String[] getPhosSiteReferences();
    public String[] getPhylomeDBReferences();
    public String[] getPIRSFReferences();
    public String[] getPmapCutDBReferences();
    public String[] getPMMA2DPageReferences();
    public String[] getPombaseReferences();
    public String[] getPptaseDBReferences();
    public String[] getPrideReferences();
    public String[] getPrintsReferences();
    public String[] getProdomReferences();
    public String[] getPromexReferences();
    public String[] getPrositeReferences();
    public String[] getProtClustDBReferences();
    public String[] getProteinModelPortalReferences();
    public String[] getProtonetReferences();
    public String[] getPseudoCapReferences();
    public String[] getRatHeart2DPageReferences();
    public String[] getRCSBPDBReferences();
    public String[] getRebaseReferences();
    public String[] getReproduction2DPageReferences();
    public String[] getRGDReferences();
    public String[] getRougeReferences();
    public String[] getSBKBReferences();
    public String[] getSGDReferences();
    public String[] getSiena2DPageReferences();
    public String[] getSmartReferences();
    public String[] getSMRReferences();
    public String[] getSourceReferences();
    public String[] getStringReferences();
    public String[] getSupfamReferences();
    public String[] getSwiss2DPageReferences();
    public String[] getTairReferences();
    public String[] getTCDBReferences();
    public String[] getTIGRFAMSReferences();
    public String[] getTuberculistReferences();
    public String[] getUCD2DPageReferences();
    public String[] getUCSCPageReferences();
    public String[] getUnipathwayReferences();
    public String[] getVectorBaseReferences();
    public String[] getWorld2DPageReferences();
    public String[] getWormBaseReferences();
    public String[] getXenBaseReferences();
    public String[] getZfinReferences();
    
    public boolean isUniref50Representant();
    public boolean isUniref90Representant();
    public boolean isUniref100Representant();
    public List<Protein> getUniref50ClusterThisProteinBelongsTo();
    public List<Protein> getUniref90ClusterThisProteinBelongsTo();
    public List<Protein> getUniref100ClusterThisProteinBelongsTo();
    public Organism getOrganism();
    public Dataset getDataset();
    public List<GenomeElement> getGenomeElements();
    public List<SubcellularLocation> getSubcellularLocations();
    public List<Interpro> getInterpro();
    public List<Pfam> getPfamTerms();
    public List<ReactomeTerm> getReactomeTerms();
    public List<Enzyme> getProteinEnzymaticActivity();
    public List<GoTerm> getGOAnnotations();
    public List<Keyword> getKeywords();
    public List<SignalPeptideFeature> getSignalPeptideFeature();
    public List<SpliceVariantFeature> getSpliceVariantFeature();
    public List<TransmembraneRegionFeature> getTransmembraneRegionFeature();
    public List<ActiveSiteFeature> getActiveSiteFeature();
    public List<FunctionComment> getFunctionComment();
    public List<PathwayComment> getPathwayComment();
    public List<DomainComment> getDomainComment();
    public List<SimilarityComment> getSimilarityComment();
    public List<ProteinProteinInteraction> getProteinOutgoingInteractions();
    public List<ProteinProteinInteraction> getProteinIncomingInteractions();
    public List<ProteinIsoformInteraction> getIsoformOutgoingInteractions();
    public List<ProteinIsoformInteraction> getIsoformIncomingInteractions();
    public List<Article> getArticleCitations();
    public List<Submission> getSubmissionCitations();
    public List<OnlineArticle> getOnlineArticleCitations();
    public List<Book> getBookCitations();
    public List<Patent> getPatentCitations();
    public List<Thesis> getThesisCitations();
    public List<UnpublishedObservation> getUnpublishedObservationsCitations();
    
    //---------------------------------------------------------------------------------------------
    //-------------------------------------SETTERS-------------------------------------------------
    //---------------------------------------------------------------------------------------------
    public void setName(String value);
    public void setFullName(String value);
    public void setShortName(String value);
    public void setAccession(String value);
    public void setSequence(String value);
    public void setModifiedDate(String value);
    public void setMass(float value);
    public void setLength(int value);
    public void setGeneNames(String[] value);
    public void setEnsemblReferences(String[] value);
    public void setKeggReferences(String[] value);
    public void setPIRReferences(String[] value);
    public void setEMBLreferences(String[] value);
    public void setEnsemblPlantsReferences(String[] value);
    public void setRefseqReferences(String[] value);
    public void setAlternativeAccessions(String[] value);
    public void setArrayExpressReferences(String[] value);
    public void setUniGeneReferences(String[] value);
    public void setDBaseEcoliReferences(String[] value);
    public void setAarhusGhent2DPageReferences(String[] value);
    public void setAGDReferences(String[] value);
    public void setAllergomeReferences(String[] value);
    public void setAnu2DPageReferences(String[] value);
    public void setArachnoServerReferences(String[] value);
    public void setBGeeReferences(String[] value);
    public void setBindingDBReferences(String[] value);
    public void setBiocycReferences(String[] value);
    public void setBrendaReferences(String[] value);
    public void setCazyReferences(String[] value);
    public void setCGDReferences(String[] value);
    public void setCHEmblReferences(String[] value);
    public void setCleanexReferences(String[] value);
    public void setCompluYeast2DPageReferences(String[] value);
    public void setConoServerReferences(String[] value);
    public void setCornea2DPageReferences(String[] value);
    public void setCTDReferences(String[] value);
    public void setCYGDReferences(String[] value);
    public void setDBSNPReferences(String[] value);
    public void setDDBJReferences(String[] value);
    public void setDictyBaseReferences(String[] value);
    public void setDIPReferences(String[] value);
    public void setDisprotReferences(String[] value);
    public void setDMDMReferences(String[] value);
    public void setDnasuReferences(String[] value);
    public void setDosacCobs2DPageReferences(String[] value);
    public void setDrugbankReferences(String[] value);
    public void setEchoBaseReferences(String[] value);
    public void setEcogeneReferences(String[] value);
    public void setEggnogReferences(String[] value);
    public void setEnsemblBacteriaReferences(String[] value);
    public void setEnsemblFungiReferences(String[] value);
    public void setEnsemblMetazoaReferences(String[] value);
    public void setEnsemblProtistsReferences(String[] value);
    public void setEuhcvDBReferences(String[] value);
    public void setEupathDBReferences(String[] value);
    public void setEvolutionaryTraceReferences(String[] value);
    public void setFlyBaseReferences(String[] value);
    public void setGenAtlasReferences(String[] value);
    public void setGenBankReferences(String[] value);
    public void setGene3DReferences(String[] value);
    public void setGeneCardsReferences(String[] value);
    public void setGeneFarmReferences(String[] value);
    public void setGeneIDReferences(String[] value);
    public void setGeneTreeReferences(String[] value);
    public void setGenevestigatorReferences(String[] value);
    public void setGenolistReferences(String[] value);
    public void setGenomeReviewsReferences(String[] value);
    public void setGenomeRNAIReferences(String[] value);
    public void setGermOnlineReferences(String[] value);
    public void setGlycoSuiteDBReferences(String[] value);
    public void setGPCRDBReferences(String[] value);
    public void setGrameneReferences(String[] value);
    public void setHINVDBReferences(String[] value);
    public void setHamapReferences(String[] value);
    public void setHGNCReferences(String[] value);
    public void setHogenomReferences(String[] value);
    public void setHovergenReferences(String[] value);
    public void setHpaReferences(String[] value);
    public void setHsspReferences(String[] value);
    public void setHugeReferences(String[] value);
    public void setIMGTReferences(String[] value);
    public void setINPARANOIDReferences(String[] value);
    public void setIntactReferences(String[] value);
    public void setIPIReferences(String[] value);
    public void setKOReferences(String[] value);
    public void setLegioListReferences(String[] value);
    public void setLepromaReferences(String[] value);
    public void setMaizeGDBReferences(String[] value);
    public void setMeropsReferences(String[] value);
    public void setMGIReferences(String[] value);
    public void setMicadoReferences(String[] value);
    public void setMIMReferences(String[] value);
    public void setMINTReferences(String[] value);
    public void setModbaseReferences(String[] value);
    public void setMycoclapReferences(String[] value);
    public void setNextbioReferences(String[] value);
    public void setNextprotReferences(String[] value);
    public void setOGPReferences(String[] value);
    public void setOMAReferences(String[] value);
    public void setOrphanetReferences(String[] value);
    public void setOrthoDBReferences(String[] value);
    public void setPantherReferences(String[] value);
    public void setPathwayInteractionDBReferences(String[] value);
    public void setPatricReferences(String[] value);
    public void setPaxDBReferences(String[] value);
    public void setPDBReferences(String[] value);
    public void setPDBJReferences(String[] value);
    public void setPDBSumReferences(String[] value);
    public void setPeptideAtlasReferences(String[] value);
    public void setPeroxibaseReferences(String[] value);
    public void setPharmGKBReferences(String[] value);
    public void setPhci2DPageReferences(String[] value);
    public void setPhosphositeReferences(String[] value);
    public void setPhosSiteReferences(String[] value);
    public void setPhylomeDBReferences(String[] value);
    public void setPIRSFReferences(String[] value);
    public void setPmapCutDBReferences(String[] value);
    public void setPMMA2DPageReferences(String[] value);
    public void setPomBaseReferences(String[] value);
    public void setPPTaseDBReferences(String[] value);
    public void setPrideReferences(String[] value);
    public void setPrintsReferences(String[] value);
    public void setProdomReferences(String[] value);
    public void setPromexReferences(String[] value);
    public void setPrositeReferences(String[] value);
    public void setProtClustDBReferences(String[] value);
    public void setProteinModelPortalReferences(String[] value);
    public void setProtonetReferences(String[] value);
    public void setPseudoCapReferences(String[] value);
    public void setRatHeart2DPageReferences(String[] value);
    public void setRCSBPDBReferences(String[] value);
    public void setRebaseReferences(String[] value);
    public void setReproduction2DPageReferences(String[] value);
    public void setRGDReferences(String[] value);
    public void setRougeReferences(String[] value);
    public void setSBKBReferences(String[] value);
    public void setSGDReferences(String[] value);
    public void setSiena2DPageReferences(String[] value);
    public void setSmartReferences(String[] value);
    public void setSMRReferences(String[] value);
    public void setSourceReferences(String[] value);
    public void setStringReferences(String[] value);
    public void setSupfamReferences(String[] value);
    public void setSwiss2DPageReferences(String[] value);
    public void setTairReferences(String[] value);
    public void setTCDBReferences(String[] value);
    public void setTIGRFAMSReferences(String[] value);
    public void setTuberculistReferences(String[] value);
    public void setUCD2DPageReferences(String[] value);
    public void setUCSCReferences(String[] value);
    public void setUnipathwayReferences(String[] value);
    public void setVectorBaseReferences(String[] value);
    public void setWorld2DPageReferences(String[] value);
    public void setWormBaseReferences(String[] value);
    public void setXenBaseReferences(String[] value);
    public void setZFINReferences(String[] value);
    
}
